spring:
  data:
    redis:
      host: localhost
      port: 6380
      timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    kr.co.csalgo: DEBUG
