spring:
  profiles:
    active: dev  # 운영 배포 시 prod 로 변경

  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: true
      additional-exclude:
        - static/**
        - public/**
    livereload:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000

verification:
  code:
    expiration: 300000

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  show-actuator: true

logging:
  level:
    root: INFO
    kr.co.csalgo: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
  file:
    name: logs/app.log

---

spring:
  config:
    activate:
      on-profile: prod

sentry:
  dsn: ${SENTRY_DSN}
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0
  environment: prod

---

spring:
  config:
    activate:
      on-profile: dev
sentry:
  dsn: ${SENTRY_DSN}
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0
  environment: dev
