spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: csalgo-web

server:
  port: 3000
  forward-headers-strategy: framework

external:
  api:
    base-url: ${EXTERNAL_API_BASE_URL:http://localhost:8080/api}
  resources:
    usage-url: ${USAGE_GUIDE_URL:https://kr.object.ncloudstorage.com/contest34-bucket-priv/resources/usage.html}
    images-url: ${IMAGE_BASE_URL:https://kr.object.ncloudstorage.com/contest34-bucket-priv/resources/images}

jwt:
  secret: ${JWT_SECRET:secret}
