spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: csalgo-web

server:
  port: 3000

external:
  api:
    base-url: ${EXTERNAL_API_BASE_URL:http://localhost:8080/api}
  resources:
    usage-url: ${USAGE_GUIDE_URL:https://kr.object.ncloudstorage.com/contest34-bucket-priv/resources/usage.html}
