spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: csalgo-server
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:csalgo}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Abc123!@#}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: true
      additional-exclude:
        - static/**
        - public/**
    livereload:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 5000

verification:
  code:
    expiration: 300000

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  show-actuator: true

logging:
  level:
    root: INFO
    kr.co.csalgo: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
  file:
    name: logs/app.log

sentry:
  dsn: ${SENTRY_DSN:}
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0
  environment: dev

jwt:
  secret: ${JWT_SECRET:testSecretKeytestSecretKeytestSecretKey}
  access-ttl-ms: 600000
  refresh-ttl-ms: 2592000000


external:
  resources:
    usage-url: ${USAGE_GUIDE_URL:https://kr.object.ncloudstorage.com/contest34-bucket-priv/resources/usage.html}
    images-url: ${IMAGE_BASE_URL:https://kr.object.ncloudstorage.com/contest34-bucket-priv/resources/images}

huggingface:
  api:
    token: ${HUGGINGFACE_API_TOKEN:token}

similarity:
  strategy: hybrid
  hybrid:
    alpha: 0.7

openai:
  model: ${OPENAI_MODEL:model}
  token: ${OPENAI_API_TOKEN:token}

