spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: test_user
    password: test_password
    jpa:
      hibernate:
        ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    kr.co.csalgo: DEBUG
    
openai:
  token: ${OPENAI_API_TOKEN:dummy-token}
  model: ${OPENAI_MODEL:gpt-4o-mini}
