spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    kr.co.csalgo: DEBUG
